// @DONE (2013-09-16 21:12)
define([
    './base64',
    './cookies',
    './core',
    './json',
    './sha1',
    './strings',
    './var/global',
    './core/BitFlags',
    './core/Enum',
    './core/Class',
    './core/ObjectArray',
    './ajax/ajax',
    './abstract/api',
    './abstract/options',
    './abstract/control',
    './abstract/subscribable',
    './ui/DialogBox',
    './ui/DialogPage',
    './ui/DialogSubpage',
    './ui/Dropdown',
    './ui/DropdownMenu',
    './ui/DropdownSelect',
    './ui/MessageBox',
    
    // Application-specific modules:
    './session',
    './toolbar',
    './ajax/RequestMethod',
    './ajax/UpsertMethod',
    './data/data',
    './data/Clients',
    './data/Dialogs',
    './data/Fields',
    './data/Keys',
    './data/Products',
    './data/RoleAcls',
    './data/Roles',
    './data/ServiceProperties',
    './data/Services',
    './data/Sites',
    './data/Tables',
    './data/Users',
    './schema/schema',
    './schema/Field',
    './schema/Link',
    './schema/Table',
    './schema/TitleBar'
], function (mdsol, global) {
    // Expose mdsol library to global object
    global.mdsol = mdsol;
});